### ISSUE TITLE
Documentation of parameters is misleading.

### ISSUE THREAD

**Issue by sasuolanderSito** [awsdocs/aws-batch-user-guide#24]
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters

Documentation state that parameters can override any job definition parameters but It seems to work only in the command section of  a job definition.

**Comment by HLeeHart** [comment]
The [parameters](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html#Batch-SubmitJob-request-parameters) member of the [SubmitJob](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html) API operation does only override parameter substitution placeholders in the [command](https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html#Batch-Type-ContainerProperties-command) member of the [containerProperties](https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html) parameter send to [RegisterJobDefinition](https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html). However, other parameters can be overridden. For example the [environment](https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerOverrides.html#Batch-Type-ContainerOverrides-environment) member of the [ContainerOverrides](https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerOverrides.html) parameter to [SubmitJob](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html) can add or replace environment variables registered with the job definition.

I agree this is somewhat confusing, because there is a parameter named `parameters`. We use different styling to differentiate the `parameters` parameter from other parameters. I'd love to hear any suggestions you have on how to make this more clear.

Thanks!

Lee Hart
AWS Documentation
